// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRSchool.DBContexts;

#nullable disable

namespace PRSchool.Migrations
{
    [DbContext(typeof(SchoolInfoContext))]
    [Migration("20220905124241_dataseed")]
    partial class dataseed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("PRSchool.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 3,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Javascript"
                        });
                });

            modelBuilder.Entity("PRSchool.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            FirstName = "Spyros",
                            LastName = "Tomaras"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            FirstName = "Agathi",
                            LastName = "Tomara"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 2,
                            FirstName = "Apostolis",
                            LastName = "Papanikoaloy"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            FirstName = "Xristoforos",
                            LastName = "Kallifonis"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 3,
                            FirstName = "Yiannis",
                            LastName = "Karakasis"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 3,
                            FirstName = "Ntinos",
                            LastName = "Nikos"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 4,
                            FirstName = "Natalia",
                            LastName = "Zachanekpliroto"
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 4,
                            FirstName = "Konstantina",
                            LastName = "Nikolatoy"
                        });
                });

            modelBuilder.Entity("PRSchool.Entities.Student", b =>
                {
                    b.HasOne("PRSchool.Entities.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("PRSchool.Entities.Course", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
