//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDatabasePartB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        // scalar properties
        public int student_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public System.DateTime birth_date { get; set; }
    }
}
